# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='person',
        ),
    ]
