# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_relations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relations',
            new_name='Relation',
        ),
    ]
