# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prioriry',
            new_name='priority',
        ),
    ]
